name: Example - Deploy Docker NPM Package

on:
  push:
    branches:
      - main

jobs:
  # see htaic/.github/.github/workflows/npm-codescan-complete.yml@main
  # npm-scan:

  # see htaic/.github/.github/workflows/npm-docker-build.yml@main
  # docker-build:

  dev-k8s-deploy:
    needs: docker-build
    uses: htaic/.github/.github/workflows/docker-env-release.yml@main
    with:
      service_name: {{ your docker image name }}
      ASSUME_ROLE: {{ your aws arn }}
      # optional 
      working_dir: .
      helm_values: {{ values.yaml to pass helm }}
      helm_source: "https://htaic.github.io/helm-charts"
      helm_chart: "htaic/microfrontend"
      cluster_name: {{ your aws cluster }}
    secrets: inherit
