name: Generate document of Terraform module

on:
  workflow_call:
    inputs:
      doc_dir:
        required: false
        description: "Operating path which document template exists"
        type: string
        default: "docs"
      doc_template:
        required: false
        description: "Document template for terraform-docs(https://terraform-docs.io/)"
        type: string
        default: ".terraform-docs.yaml"
      commit_msg:
        required: false
        description: "Commit message for generated document"
        type: string
        default: "docs: Update from github actions"

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    name: Generate document and commit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install terraform-docs
        working-directory: ${{ inputs.doc_dir }}
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs

      - name: Render terraform docs
        run: |
          ${{ inputs.doc_dir }}/terraform-docs -c ${{ inputs.doc_dir }}/${{ inputs.doc_template }} --output-file README.md .

      - name: Commit changes
        id: commit
        run: |
          git config user.name "${{ github.actor }}" && \
          git config user.email "<>" && \
          git add README.md
          git diff-index --quiet HEAD || git commit -m "${{ inputs.commit_msg }}" && \
          git push
        continue-on-error: false
