name: Lint Terraform module

on:
  workflow_call:
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      commit_msg:
        required: false
        description: "Commit message for linted code"
        type: string
        default: "chore: Linting from github actions"

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting code and commit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        working-directory: ${{ inputs.working_dir }}
        id: fmt
        run: terraform fmt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '*'
          message: ${{ inputs.commit_msg }}
