# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Zip and upload python script to s3

on:
  workflow_call:
    inputs:
#      aws_access_key_id:
#        required: true
#        type: string
#      aws_secret_access_key:
#        required: true
#        type: string
      s3_bucket_name:
        required: true
        type: string
      s3_key_prefix:
        required: true
        type: string
      package_name:
        required: true
        type: string
      package_path:
        required: false
        type: string
      environment:
        required: true
        type: string
        default: dev
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: actions/checkout@v3
      
      - name:  Create archive
        run: tar -czvf ${{ inputs.package_name }} ${{ inputs.package_path }}

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks
            source_dir: "temp"
            s3_bucket: ${{ inputs.s3_bucket_name }}
            s3_key_prefix: ${{ inputs.s3_key_prefix }}
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
