# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Zip and upload python script to s3

on:
  workflow_call:
    inputs:
      aws_access_key_id:
        required: true
        type: string
      aws_secret_access_key:
        required: true
        type: string
      s3_bucket_name:
        required: true
        type: string
      s3_key_prefix:
        required: true
        type: string
      package_name:
        required: true
        type: string
      package_path:
        required: false
        type: string
      environment:
        required: true
        type: string
        default: dev
#    secrets:
#      AWS_ACCESS_KEY_ID:
#        required: true
#      AWS_SECRET_ACCESS_KEY:
#        required: true
#      AWS_REGION:
#        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      
      - name:  Create archive
        run: tar -czvf ${{ inputs.package_name }} ${{ inputs.package_path }}

      - name: Upload file to bucket
        uses: a-sync/s3-uploader@master
        with:
          args: --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
          AWS_REGION: 'us-west-2'
          S3_BUCKET: ${{ inputs.s3_bucket_name }}
          S3_KEY: ${{ inputs.s3_key_prefix }}
          FILE: ${{ inputs.package_name }}
